config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'admin', :to => 'admin#index'

  resources :responses
  resources :messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/response.rb
class Response < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with :name => "admin", :password => "alienz", only: :index

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @messages = Message.all
    @array = @messages.order("RANDOM()")
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate, :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == 'alienz'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:content, :threat)
    end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :authenticate, :set_response, only: [:show, :edit, :update, :destroy]

  # GET /responses
  # GET /responses.json
  def index
    @responses = Response.all
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
  end

  # GET /responses/new
  def new
    @response = Response.new
  end

  # GET /responses/1/edit
  def edit
  end

  # POST /responses
  # POST /responses.json
  def create
    @response = Response.new(response_params)

    respond_to do |format|
      if @response.save
        format.html { redirect_to @response, notice: 'Response was successfully created.' }
        format.json { render :show, status: :created, location: @response }
      else
        format.html { render :new }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responses/1
  # PATCH/PUT /responses/1.json
  def update
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { render :show, status: :ok, location: @response }
      else
        format.html { render :edit }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response.destroy
    respond_to do |format|
      format.html { redirect_to responses_url, notice: 'Response was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == 'alienz'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_response
      @response = Response.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def response_params
      params.require(:response).permit(:content, :threat)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/admin/index.html.erb
<h1>Chatbot Admin</h1>

<p><a href='/messages'>Change the messages (from humankind to the alien overload)</a></p>

app/views/home/index.html.erb
<div class='alienmessage' id='1'>
  <img class='alienprofile' src='https://media.giphy.com/media/r9u2BEXZUzGo/giphy.gif'>
  <div class='alienchatbox'>
    <p>Greetings, human. My name is Vlop, your</p>
    <p>new alien overlord.</p>
    <p>What do you have to say on behalf of humankind?<p>
  </div>
</div>

<div class='selector'>
  <div class='question'>How do you want to respond?</div>
  <div class='options'>
    <a href='#'><div class='first option'>
      <%=
      if @array[0] == nil
        'Admin? Add a message'
      else
        @array[0].content
      end
      %>
    </div></a>
    <a href='#'><div class='second option'>
      <%=
      if @array[1] == nil
        'Admin? Add a message'
      else
        @array[1].content
      end
      %>
    </div></a>
    <a href='#'><div class='third option'>
      <%=
      if @array[2] == nil
        'Admin? Add a message'
      else
        @array[2].content
      end
      %>
    </div></a>
  </div>
  <div class='options'>
    <a href='#'><div class='fourth option'>
      <%=
      if @array[3] == nil
        'Admin? Add a message'
      else
        @array[3].content
      end
      %>
    </div></a>
    <a href='#'><div class='fifth option'>
      <%=
      if @array[4] == nil
        'Admin? Add a message'
      else
        @array[4].content
      end
      %>
    </div></a>
    <a href='#'><div class='sixth option'>
      <%=
      if @array[5] == nil
        'Admin? Add a message'
      else
        @array[5].content
      end
      %>
    </div></a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatbot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div style='padding-top: 30px'></div>
    <%= yield %>
  </body>

  <footer>
    Made with ❤️ by <a href='https://github.com/baileytalks'>@baileytalks</a>  –  Find the admin area => <a href='/admin'>here</a>
  </footer>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :message_content %>
  </div>

  <div class="field">
    <%= form.label :threat %>
    <%= form.text_field :threat, "size" => 1, id: :message_threat %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages from humankind to the alien overload</h1>

<p>Here are the messages that humankind can send to the alien overload.</p>
<p>Threat levels go from 1 (safe) to 3 (dangerous):</p>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.content %></td>
        <td><%= message.threat %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>
<h3>(from humankind to the alien overload)</h3>

<p>Threat level goes from 1 (safe) to 3 (dangerous)</p>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <strong>Threat level:</strong>
<%= @message.threat %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/responses/_form.html.erb
<%= form_with(model: response, local: true) do |form| %>
  <% if response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :response_content %>
  </div>

  <div class="field">
    <%= form.label :threat %>
    <%= form.text_field :threat, "size" => 1, id: :response_threat %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing Response</h1>

<%= render 'form', response: @response %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Responses from the alien overload</h1>

<p>Here are the responses that the alien overload can send back. Threat levels go from 1 (safe) to 3 (dangerous):</p>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= response.content %></td>
        <td><%= response.threat %></td>
        <td><%= link_to 'Show', response %></td>
        <td><%= link_to 'Edit', edit_response_path(response) %></td>
        <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Response', new_response_path %>

app/views/responses/new.html.erb
<h1>New Response</h1>
<h3>(from alien overload to humankind)</h3>

<p>Threat level goes from 1 (safe) to 3 (dangerous)</p>

<%= render 'form', response: @response %>

<%= link_to 'Back', responses_path %>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @response.content %>
  <%= @response.threat %>
</p>

<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', responses_path %>